# config sheet for our conglomerate of docker files !
# kind of like a bullet specification list --> like a spec sheet

version: '3'
services:
  app:
    build: .
    container_name: orva-take-home
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/orvatakehome
      - NODE_ENV=development
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13-alpine
    container_name: ovra-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orvatakehome
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: